"""Bounded online discovery of emerging fraud behaviours.

The transaction decision stack answers "should this authorization receive
friction?". This module answers a different question: "are multiple suspicious
authorizations beginning to form a coherent behaviour we have not named yet?"

It deliberately does not consume ``label_hint`` when clustering. In the arena we
know which rows were generated by an attack, but a real issuer would not know
that at authorization time. Simulator truth is retained only as an optional
post-hoc diagnostic in fingerprints.

The miner uses small normalized behavioural vectors and online cosine
micro-clusters. It is intentionally bounded and allocation-light so discovery can
run beside the authorization path without turning a hackathon demo into an
unbounded sklearn clustering job.
"""

from __future__ import annotations

import math
from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Iterable


@dataclass(slots=True)
class _Cluster:
    cluster_id: str
    centroid: list[float]
    count: int
    first_seen: float
    last_seen: float
    anomaly_count: int = 0
    ring_count: int = 0
    simulator_attack_count: int = 0
    decisions: Counter = field(default_factory=Counter)
    merchants: Counter = field(default_factory=Counter)
    modes: Counter = field(default_factory=Counter)
    tds: Counter = field(default_factory=Counter)
    sample_txns: list[str] = field(default_factory=list)


class ThreatMiner:
    """Online micro-clusterer over suspicious authorization behaviour."""

    def __init__(
        self,
        *,
        similarity_threshold: float = 0.88,
        min_cluster_size: int = 3,
        max_clusters: int = 64,
        sample_size: int = 8,
    ) -> None:
        if not 0.0 < similarity_threshold <= 1.0:
            raise ValueError("similarity_threshold must be in (0, 1]")
        if min_cluster_size < 2:
            raise ValueError("min_cluster_size must be >= 2")
        if max_clusters < 1:
            raise ValueError("max_clusters must be >= 1")
        self.similarity_threshold = similarity_threshold
        self.min_cluster_size = min_cluster_size
        self.max_clusters = max_clusters
        self.sample_size = sample_size
        self._clusters: list[_Cluster] = []
        self._next_id = 1
        self.events_considered = 0
        self.events_clustered = 0

    @staticmethod
    def _clip(value: float, upper: float) -> float:
        return max(0.0, min(float(value), upper))

    @classmethod
    def _vector(cls, record: dict) -> list[float]:
        """Compact scale-normalized structural/behavioural representation."""
        features = record.get("features", {})
        scores = record.get("scores", {})
        return [
            cls._clip(features.get("cust_txn_count_10m", 0), 20.0) / 8.0,
            cls._clip(features.get("dev_txn_count_10m", 0), 30.0) / 10.0,
            cls._clip(features.get("merch_txn_count_10m", 0), 50.0) / 20.0,
            cls._clip(features.get("merch_distinct_custs_10m", 0), 40.0) / 16.0,
            cls._clip(features.get("amount_over_mean30", 0), 10.0) / 4.0,
            cls._clip(features.get("cust_mcc_distinct_1h", 0), 10.0) / 5.0,
            cls._clip(scores.get("velocity", 0), 1.0),
            cls._clip(max(float(scores.get("novelty_anomaly", 0.0)), 0.0), 1.0),
            cls._clip(scores.get("ring_risk", 0), 1.0),
            1.0 if scores.get("ring_detected") else 0.0,
        ]

    @staticmethod
    def _cosine(left: Iterable[float], right: Iterable[float]) -> float:
        a = list(left)
        b = list(right)
        dot = sum(x * y for x, y in zip(a, b))
        na = math.sqrt(sum(x * x for x in a))
        nb = math.sqrt(sum(y * y for y in b))
        if na == 0.0 or nb == 0.0:
            return 0.0
        return dot / (na * nb)

    @staticmethod
    def _timestamp(record: dict) -> float:
        raw = record.get("payload", {}).get("timestamp")
        if isinstance(raw, datetime):
            value = raw
        elif isinstance(raw, str):
            value = datetime.fromisoformat(raw.replace("Z", "+00:00"))
        else:
            value = datetime.now(timezone.utc)
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value.timestamp()

    @staticmethod
    def _is_candidate(record: dict) -> bool:
        scores = record.get("scores", {})
        return bool(
            record.get("decision") != "APPROVE"
            or scores.get("is_anomaly")
            or float(scores.get("ring_risk", 0.0)) >= 0.08
            or float(scores.get("velocity", 0.0)) >= 0.55
        )

    def _new_cluster(self, vector: list[float], ts: float) -> _Cluster:
        if len(self._clusters) >= self.max_clusters:
            # Bounded memory: replace the least recently active tiny cluster
            # first, otherwise the globally stalest cluster.
            victim = min(
                self._clusters,
                key=lambda item: (item.count >= self.min_cluster_size, item.last_seen),
            )
            self._clusters.remove(victim)
        cluster = _Cluster(
            cluster_id=f"EMERGENT_{self._next_id:04d}",
            centroid=list(vector),
            count=0,
            first_seen=ts,
            last_seen=ts,
        )
        self._next_id += 1
        self._clusters.append(cluster)
        return cluster

    def _choose_cluster(self, vector: list[float], ts: float) -> tuple[_Cluster, float]:
        if not self._clusters:
            return self._new_cluster(vector, ts), 1.0
        scored = [(self._cosine(vector, item.centroid), item) for item in self._clusters]
        similarity, best = max(scored, key=lambda pair: pair[0])
        if similarity < self.similarity_threshold:
            return self._new_cluster(vector, ts), similarity
        return best, similarity

    @staticmethod
    def _bump_centroid(cluster: _Cluster, vector: list[float]) -> None:
        old_n = cluster.count
        new_n = old_n + 1
        if old_n == 0:
            cluster.centroid[:] = vector
            return
        for index, value in enumerate(vector):
            cluster.centroid[index] += (value - cluster.centroid[index]) / new_n

    def _update_cluster(self, cluster: _Cluster, record: dict, vector: list[float], ts: float) -> None:
        self._bump_centroid(cluster, vector)
        cluster.count += 1
        cluster.last_seen = max(cluster.last_seen, ts)
        scores = record.get("scores", {})
        cluster.anomaly_count += int(bool(scores.get("is_anomaly")))
        cluster.ring_count += int(bool(scores.get("ring_detected")))
        cluster.simulator_attack_count += int(bool(record.get("label_hint")))
        cluster.decisions[str(record.get("decision", "UNKNOWN"))] += 1

        payload = record.get("payload", {})
        merchant = payload.get("merchant_id")
        if merchant:
            cluster.merchants[str(merchant)] += 1
        mode = payload.get("pos_entry_mode")
        if mode:
            cluster.modes[str(mode)] += 1
        tds = payload.get("3ds_status")
        if tds:
            cluster.tds[str(tds)] += 1
        txn = payload.get("transaction_id")
        if txn and len(cluster.sample_txns) < self.sample_size:
            cluster.sample_txns.append(str(txn))

    @staticmethod
    def _top(counter: Counter, n: int = 3) -> list[dict]:
        return [{"value": key, "count": count} for key, count in counter.most_common(n)]

    def _fingerprint(self, cluster: _Cluster, similarity: float | None = None) -> dict:
        n = max(cluster.count, 1)
        anomaly_rate = cluster.anomaly_count / n
        ring_rate = cluster.ring_count / n
        friction_rate = 1.0 - cluster.decisions.get("APPROVE", 0) / n
        confidence = min(
            0.99,
            0.35
            + 0.10 * math.log1p(cluster.count)
            + 0.18 * anomaly_rate
            + 0.16 * ring_rate
            + 0.10 * friction_rate,
        )
        if cluster.count >= 10:
            status = "established"
        elif cluster.count >= self.min_cluster_size:
            status = "emerging"
        else:
            status = "candidate"
        return {
            "threat_id": cluster.cluster_id,
            "status": status,
            "transactions": cluster.count,
            "first_seen": datetime.fromtimestamp(cluster.first_seen, timezone.utc).isoformat(),
            "last_seen": datetime.fromtimestamp(cluster.last_seen, timezone.utc).isoformat(),
            "novelty_confidence": round(confidence, 4),
            "anomaly_rate": round(anomaly_rate, 4),
            "ring_rate": round(ring_rate, 4),
            "friction_rate": round(friction_rate, 4),
            "top_decisions": self._top(cluster.decisions),
            "top_merchants": self._top(cluster.merchants),
            "top_entry_modes": self._top(cluster.modes),
            "top_3ds": self._top(cluster.tds),
            "sample_transaction_ids": list(cluster.sample_txns),
            # This field is explicitly evaluation-only. It is never read by the
            # clustering algorithm and can be removed in a production adapter.
            "simulator_attack_fraction": round(cluster.simulator_attack_count / n, 4),
            "similarity_to_cluster": None if similarity is None else round(similarity, 4),
        }

    def observe(self, record: dict) -> dict | None:
        """Consume one decision and optionally emit a newly meaningful fingerprint."""
        self.events_considered += 1
        if not self._is_candidate(record):
            return None
        vector = self._vector(record)
        ts = self._timestamp(record)
        cluster, similarity = self._choose_cluster(vector, ts)
        self._update_cluster(cluster, record, vector, ts)
        self.events_clustered += 1

        # Emit at meaningful growth points rather than on every transaction.
        if (
            cluster.count == self.min_cluster_size
            or cluster.count in {5, 10}
            or (cluster.count >= 25 and cluster.count % 25 == 0)
        ):
            return self._fingerprint(cluster, similarity)
        return None

    def snapshot(self, *, include_candidates: bool = False) -> list[dict]:
        rows = [
            self._fingerprint(cluster)
            for cluster in self._clusters
            if include_candidates or cluster.count >= self.min_cluster_size
        ]
        return sorted(
            rows,
            key=lambda row: (row["status"] == "established", row["transactions"]),
            reverse=True,
        )

    def diagnostics(self) -> dict:
        visible = self.snapshot()
        return {
            "events_considered": self.events_considered,
            "events_clustered": self.events_clustered,
            "microclusters": len(self._clusters),
            "emerging_or_established": len(visible),
        }


__all__ = ["ThreatMiner"]
