"use client";

/**
 * The Adversarial Payment Arena — SOC dashboard (single page).
 *
 * Left:   the attacker's mind (planner/operator thoughts, payloads, gate verdicts)
 *         + the running cost matrix in bps.
 * Center: the entity graph lighting up as rings form + AI field notes.
 * Right:  the defense stack's decisions with per-layer scores.
 *
 * All live data arrives over one WebSocket (src/lib/ws.ts); this component
 * owns the connection lifecycle and folds events into reducer state.
 */

import { useCallback, useEffect, useReducer, useRef, useState } from "react";
import { toast } from "sonner";

import { AnalystPanel, type AnalystStats } from "@/components/arena/analyst-panel";
import { AttackerFeed, type CheckRow, type PayloadRow, type ThoughtRow } from "@/components/arena/attacker-feed";
import { ControlBar } from "@/components/arena/control-bar";
import { CostPanel } from "@/components/arena/cost-panel";
import { DefenseFeed, type DecisionRow } from "@/components/arena/defense-feed";
import { EntityGraphCanvas } from "@/components/arena/graph-canvas";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { ArenaEvent, CampaignSummaryData, CostUpdate, GraphEdge, GraphNode } from "@/lib/arena-types";
import { ArenaSocket, backendHttpUrl, backendWsUrl, type ConnState } from "@/lib/ws";

// --------------------------------------------------------------------------- //
// State
// --------------------------------------------------------------------------- //

interface ArenaState {
  thoughts: ThoughtRow[];
  payloads: PayloadRow[];
  checks: CheckRow[];
  decisions: DecisionRow[];
  costs: CostUpdate | null;
  summary: CampaignSummaryData | null;
  graphNodes: GraphNode[];
  graphEdges: GraphEdge[];
  running: boolean;
}

const initialState: ArenaState = {
  thoughts: [],
  payloads: [],
  checks: [],
  decisions: [],
  costs: null,
  summary: null,
  graphNodes: [],
  graphEdges: [],
  running: false,
};

const CAPS = { thoughts: 120, payloads: 60, checks: 150, decisions: 150, graphNodes: 160, graphEdges: 220 };

// --------------------------------------------------------------------------- //
// Guided demo ("Judge Mode")
// --------------------------------------------------------------------------- //

const GUIDED_ATTACK = "attack_2_synthetic_mule_ring";
const GUIDED_SIZE = 25;

/**
 * The scripted 90-second walkthrough. Steps advance on real WebSocket events,
 * never on timers, so the narration cannot drift ahead of the fight.
 */
const GUIDED_STEPS: string[] = [
  "Guided demo: a synthetic mule ring is being spun up. Left = the attacker's reasoning, center = the entity graph, right = the defense stack's verdicts.",
  "The red-team agent plans each payload. Before anything reaches the defense, the plausibility gate rejects economically irrational or rail-infeasible traffic.",
  "Payloads are clearing the gate: coherent amounts, valid rails, plausible metadata. Real fraud looks like this — nothing obviously broken per transaction.",
  "The graph layer fires: shared device/IP across 'unrelated' customer profiles. No single account trips a threshold — the ring is only visible in topology.",
  "The cost matrix declines the ring. Blocking it is priced against the customer-insult cost of a false positive — an explicit dollar trade-off, not a static rule.",
  "Campaign over. Every number on this page is regenerated by `make reproduce` and mapped claim-by-claim on the evidence ledger.",
];

/**
 * REPLAY FALLBACK source: a real campaign recorded at the backend's own
 * pacing (frontend/public/arena/replay.json). Played only when the live
 * WebSocket cannot connect within 3s, so the page is never blank behind an
 * unreachable backend. env_seed is the environment's fixed seed, recorded
 * alongside its provenance string.
 */
interface ReplayDoc {
  env_seed: number;
  env_seed_source: string;
  events: { t_ms: number; event: ArenaEvent }[];
}

type Action = { type: "reset" } | { type: "event"; event: ArenaEvent };

function capped<T>(arr: T[], cap: number): T[] {
  return arr.length > cap ? arr.slice(arr.length - cap) : arr;
}

function reducer(state: ArenaState, action: Action): ArenaState {
  switch (action.type) {
    case "reset":
      return {
        ...state,
        thoughts: [],
        payloads: [],
        checks: [],
        decisions: [],
        summary: null,
        running: true,
      };
    case "event": {
      const e = action.event;
      switch (e.type) {
        case "agent_thought":
          return {
            ...state,
            thoughts: capped(
              [...state.thoughts, { id: Date.now() + Math.random(), role: e.role, text: e.data, txn: e.txn_index }],
              CAPS.thoughts,
            ),
          };
        case "payload_generated":
          return {
            ...state,
            payloads: capped(
              [...state.payloads, { id: Date.now() + Math.random(), payload: e.data, txn: e.txn_index }],
              CAPS.payloads,
            ),
          };
        case "plausibility_check":
          return {
            ...state,
            checks: capped(
              [
                ...state.checks,
                {
                  id: Date.now() + Math.random(),
                  ok: e.data.accepted,
                  reason: e.data.reason,
                  attempt: e.data.attempt,
                  txn: e.txn_index,
                },
              ],
              CAPS.checks,
            ),
          };
        case "defense_decision":
          return {
            ...state,
            decisions: capped(
              [
                ...state.decisions,
                {
                  id: Date.now() + Math.random(),
                  txn: e.txn_index,
                  decision: e.decision,
                  reasons: e.reasons,
                  scores: e.scores,
                  amount: e.amount,
                },
              ],
              CAPS.decisions,
            ),
          };
        case "cost_update": {
          const costs: CostUpdate = {
            fp_cost_bps: e.fp_cost_bps,
            fp_cost_usd: e.fp_cost_usd,
            fn_loss: e.fn_loss,
            tp_saved: e.tp_saved,
            net_savings: e.net_savings,
            counts: e.counts,
          };
          return { ...state, costs };
        }
        case "graph_update": {
          const nodeMap = new Map(state.graphNodes.map((n) => [n.id, n]));
          for (const n of e.nodes) nodeMap.set(n.id, n);
          const edgeMap = new Map(
            state.graphEdges.map((x) => [`${x.source}->${x.target}`, x] as const),
          );
          for (const x of e.edges) edgeMap.set(`${x.source}->${x.target}`, x);
          const graphNodes = capped([...nodeMap.values()], CAPS.graphNodes);
          const keepIds = new Set(graphNodes.map((n) => n.id));
          const graphEdges = capped(
            [...edgeMap.values()].filter((x) => keepIds.has(x.source) && keepIds.has(x.target)),
            CAPS.graphEdges,
          );
          return { ...state, graphNodes, graphEdges };
        }
        case "campaign_summary":
          return { ...state, summary: e.data, running: false };
        case "campaign_accepted":
          return state; // control-side only
        default:
          return state;
      }
    }
  }
}

// --------------------------------------------------------------------------- //
// Page
// --------------------------------------------------------------------------- //

export default function ArenaPage() {
  const [state, dispatch] = useReducer(reducer, initialState);
  const [conn, setConn] = useState<ConnState>("idle");
  const [turbo, setTurbo] = useState(false);
  const [guidedStep, setGuidedStep] = useState<number | null>(null);
  const [hero, setHero] = useState<{ netInr: number | null; gate: string | null }>({
    netInr: null,
    gate: null,
  });
  const socketRef = useRef<ArenaSocket | null>(null);
  const ringToastedRef = useRef(false);
  const guidedRef = useRef<number | null>(null);
  const [replay, setReplay] = useState<ReplayDoc | null>(null);
  const connRef = useRef<ConnState>("idle");
  const replayTimersRef = useRef<ReturnType<typeof setTimeout>[]>([]);

  const setGuided = useCallback((step: number | null) => {
    guidedRef.current = step;
    setGuidedStep(step);
  }, []);

  // Hero numbers come from the same artifacts the /evidence page renders —
  // the header cannot show a figure the evidence API would not serve.
  useEffect(() => {
    const base = backendHttpUrl();
    fetch(`${base}/api/evidence/summary`, { cache: "no-store" })
      .then((r) => {
        if (!r.ok) console.warn(`evidence API ${r.status} — hero badge suppressed`);
        return r.ok ? r.json() : null;
      })
      .then((s) => {
        if (s) setHero((h) => ({ ...h, netInr: s.net_benefit_inr_at_production_prevalence ?? null }));
      })
      .catch((err) => console.warn("evidence API unreachable — hero badge suppressed", err));
    fetch(`${base}/api/evidence/artifact/fidelity_report`, { cache: "no-store" })
      .then((r) => {
        if (!r.ok) console.warn(`evidence API ${r.status} — hero badge suppressed`);
        return r.ok ? r.json() : null;
      })
      .then((f) => {
        const agg = f?.aggregated;
        const copula = agg?.gaussian_copula?.c2st_auc?.mean;
        const indep = agg?.independent_marginal?.c2st_auc?.mean;
        if (typeof copula === "number" && typeof indep === "number")
          setHero((h) => ({
            ...h,
            gate: `C2ST ${copula.toFixed(3)} vs ${indep.toFixed(3)} — fidelity separates generators`,
          }));
      })
      .catch((err) => console.warn("evidence API unreachable — hero badge suppressed", err));
  }, []);

  // ---- WebSocket lifecycle: connect once, reconnect forever ---------------
  useEffect(() => {
    const handle = (e: ArenaEvent) => {
      // side-effects that must not live in the reducer
      if (e.type === "defense_decision") {
        if (e.decision === "DECLINE") {
          toast.error(`TXN ${e.txn_index ?? "?"} DECLINED`, {
            description: e.reasons.join(", ") || "policy",
            duration: 3500,
          });
        }
        if (e.scores.ring_detected && !ringToastedRef.current) {
          ringToastedRef.current = true;
          toast.warning("Mule ring detected in entity graph", {
            description: `shared infra across 3+ profiles (${e.scores.ring_id ?? "?"})`,
          });
        }
      }
      if (e.type === "campaign_summary") {
        toast.success(`Campaign complete — ${e.data.accepted}/${e.data.txn_slots} landed`, {
          description: `net vs tooling: $${e.data.net_vs_tooling_usd.toLocaleString()} · ${e.data.llm_calls} LLM calls`,
          duration: 8000,
        });
      }
      if (e.type === "error") {
        toast.error("Backend rejected the request", { description: String(e.data) });
      }

      // Guided demo narration: advance only on the event that proves the step.
      const step = guidedRef.current;
      if (step !== null) {
        if (step === 0 && e.type === "agent_thought") setGuided(1);
        else if (step === 1 && e.type === "plausibility_check" && e.data.accepted) setGuided(2);
        else if (step === 2 && e.type === "defense_decision" && e.scores.ring_detected) setGuided(3);
        else if (step === 3 && e.type === "defense_decision" && e.decision === "DECLINE") setGuided(4);
        else if (e.type === "campaign_summary" && step < GUIDED_STEPS.length - 1) {
          setGuided(GUIDED_STEPS.length - 1);
        }
      }

      dispatch({ type: "event", event: e });
    };

    const onState = (cs: ConnState) => {
      connRef.current = cs;
      setConn(cs);
      if (cs === "open") {
        // Live took over: cancel any replay in flight and clear its badge.
        for (const t of replayTimersRef.current) clearTimeout(t);
        replayTimersRef.current = [];
        setReplay(null);
      }
    };

    const socket = new ArenaSocket(backendWsUrl(), { onEvent: handle, onState });
    socketRef.current = socket;
    socket.connect();

    // REPLAY FALLBACK: if the live socket has not opened within 3s, play the
    // recorded campaign at its original cadence through the same dispatch path
    // — the page must never be blank behind an unreachable backend.
    const failTimer = setTimeout(() => {
      if (connRef.current === "open") return;
      fetch("/arena/replay.json", { cache: "no-store" })
        .then((r) => {
          if (!r.ok) {
            console.warn(`GET /arena/replay.json → ${r.status}`);
            return null;
          }
          return r.json() as Promise<ReplayDoc>;
        })
        .then((doc) => {
          if (!doc || !Array.isArray(doc.events) || doc.events.length === 0) {
            console.warn("GET /arena/replay.json — unusable recording (no events)");
            return;
          }
          if (connRef.current === "open") return; // live arrived meanwhile
          setReplay(doc);
          dispatch({ type: "reset" });
          for (const ev of doc.events) {
            replayTimersRef.current.push(
              setTimeout(() => {
                if (connRef.current === "open") return; // live takes precedence
                handle(ev.event);
              }, ev.t_ms),
            );
          }
        })
        .catch((err) => console.warn("GET /arena/replay.json failed", err));
    }, 3000);

    return () => {
      clearTimeout(failTimer);
      for (const t of replayTimersRef.current) clearTimeout(t);
      replayTimersRef.current = [];
      socket.close();
    };
  }, [setGuided]);

  const launch = useCallback(
    (attackFile: string, size: number) => {
      dispatch({ type: "reset" });
      const ok = socketRef.current?.send({
        type: "start_campaign",
        attack_file: attackFile,
        campaign_size: size,
        ...(turbo ? { sleep_s: 0 } : {}),
      });
      if (!ok) toast.error("Socket not open yet", { description: "wait for LIVE badge" });
    },
    [turbo],
  );

  const startGuidedDemo = useCallback(() => {
    dispatch({ type: "reset" });
    const ok = socketRef.current?.send({
      type: "start_campaign",
      attack_file: GUIDED_ATTACK,
      campaign_size: GUIDED_SIZE,
      sleep_s: 0,
    });
    if (ok) {
      setGuided(0);
    } else {
      toast.error("Socket not open yet", { description: "wait for LIVE badge" });
    }
  }, [setGuided]);

  const getStats = useCallback((): AnalystStats => {
    return {
      costs: state.costs,
      decisions: state.decisions.slice(-20).map((d) => ({
        decision: d.decision,
        velocity: d.scores.velocity,
        ring: d.scores.ring_detected,
        amount: d.amount,
      })),
      summary: state.summary as Record<string, unknown> | null,
    };
  }, [state]);

  return (
    <main className="mx-auto flex h-screen max-w-[1800px] flex-col gap-3 p-4">
      <header className="flex flex-wrap items-center justify-between gap-2">
        <div>
          <h1 className="type-ui text-lg font-bold tracking-tight text-text">
            ADVERSARIAL PAYMENT ARENA
            <span className="type-ui ml-2 text-xs font-normal text-text-dim">
              Identify → Generate → Defend
            </span>
          </h1>
          <p className="type-ui text-[11px] text-text-dim">
            LLM fraud campaigns vs. a simulated issuer stack — every thought, gate verdict, and decision, live.
          </p>
          <p className="type-ui mt-0.5 text-[10px] text-text-dim">
            <span className="text-red">red = attacker / loss</span>
            {" · "}
            <span className="text-blue">blue = defender / gate</span>
          </p>
        </div>
        <div className="flex items-center gap-2">
          {replay && (
            <Badge
              variant="outline"
              className="type-ui border-warn/60 text-[9.5px] font-semibold text-warn"
              title={replay.env_seed_source}
            >
              REPLAY · seed {replay.env_seed} · live backend unavailable
            </Badge>
          )}
          {hero.netInr !== null && (
            <Badge variant="outline" className="type-num border-pass/60 text-[9.5px] text-pass">
              {new Intl.NumberFormat("en-IN", {
                style: "currency",
                currency: "INR",
                notation: "compact",
                maximumFractionDigits: 1,
              }).format(hero.netInr)}{" "}
              net / 1M auths
            </Badge>
          )}
          {hero.gate && (
            <Badge variant="outline" className="type-num border-blue/60 text-[9.5px] text-blue">
              {hero.gate}
            </Badge>
          )}
          <Badge variant="outline" className="type-ui border-border-hi text-[9.5px] text-text-dim">
            XGBoost · iForest · NetworkX
          </Badge>
          <Badge variant="outline" className="type-ui border-red/60 text-[9.5px] text-red">
            red team: LLM (OpenRouter)
          </Badge>
          <a
            href="/evidence"
            className="type-ui text-[9.5px] text-blue underline underline-offset-2 transition-colors hover:text-blue/80"
          >
            evidence &amp; claim ledger →
          </a>
        </div>
      </header>

      <ControlBar
        conn={conn}
        running={state.running}
        turbo={turbo}
        onTurboChange={setTurbo}
        onLaunch={launch}
        onGuidedDemo={startGuidedDemo}
      />

      {guidedStep !== null && (
        <div className="flex items-center gap-3 rounded-[var(--r-md)] border border-blue/50 bg-blue-dim px-4 py-2.5">
          <div className="flex items-center gap-1.5">
            {GUIDED_STEPS.map((_, i) => (
              <span
                key={i}
                className={`h-1.5 w-1.5 rounded-full ${
                  i < guidedStep ? "bg-blue/50" : i === guidedStep ? "bg-blue" : "bg-border-hi"
                }`}
              />
            ))}
          </div>
          <p className="type-ui min-w-0 flex-1 text-[12px] leading-snug text-text">
            {GUIDED_STEPS[guidedStep]}
            {guidedStep === GUIDED_STEPS.length - 1 && (
              <a href="/evidence" className="type-ui ml-2 text-[11px] text-blue underline underline-offset-2">
                open /evidence →
              </a>
            )}
          </p>
          <button
            onClick={() => setGuided(null)}
            className="type-ui text-[10px] text-text-faint transition-colors hover:text-text-dim"
          >
            dismiss
          </button>
        </div>
      )}

      <div className="grid min-h-0 flex-1 gap-3 lg:grid-cols-[360px_1fr_420px]">
        {/* ---- left: attacker mind + money ---- */}
        <div className="flex min-h-0 flex-col gap-3">
          <AttackerFeed thoughts={state.thoughts} payloads={state.payloads} checks={state.checks} />
          <CostPanel costs={state.costs} />
        </div>

        {/* ---- center: the graph + analyst ---- */}
        <div className="flex min-h-0 flex-col gap-3">
          <Card className="flex min-h-0 flex-1 flex-col overflow-hidden border-border bg-surface-1">
            <CardHeader className="pb-1">
              <CardTitle className="type-ui text-sm">
                Entity Graph
                <span className="type-ui ml-2 text-[10px] font-normal text-text-dim">
                  red = shared infra (ring signal) · {state.graphNodes.length} nodes
                </span>
              </CardTitle>
            </CardHeader>
            <CardContent className="min-h-0 flex-1 p-0">
              <EntityGraphCanvas nodes={state.graphNodes} edges={state.graphEdges} className="h-full w-full" />
            </CardContent>
          </Card>
          <div className="h-[230px]">
            <AnalystPanel getStats={getStats} />
          </div>
        </div>

        {/* ---- right: defense + campaign summary ---- */}
        <div className="flex min-h-0 flex-col gap-3">
          <DefenseFeed rows={state.decisions} />
          {state.summary && (
            <Card className="border-border bg-surface-1">
              <CardHeader className="pb-1">
                <CardTitle className="type-ui text-sm">Last Campaign</CardTitle>
              </CardHeader>
              <CardContent className="type-num grid grid-cols-2 gap-x-4 gap-y-1 text-[10.5px] text-text-dim">
                <span>spec</span>
                <span className="text-right text-text">{state.summary.spec_id.replace("ATTACK_", "")}</span>
                <span>landed</span>
                <span className="text-right text-text">
                  {state.summary.accepted}/{state.summary.txn_slots} ({Math.round(state.summary.accept_rate * 100)}%)
                </span>
                <span>gate rejects</span>
                <span className="text-right text-text">
                  {Object.entries(state.summary.gate_rejects).map(([k, v]) => `${k}:${v}`).join(" ") || "0"}
                </span>
                <span>LLM calls</span>
                <span className="text-right text-text">{state.summary.llm_calls}</span>
                <span>gross attempted</span>
                <span className="text-right text-red">${state.summary.gross_value_usd.toLocaleString()}</span>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </main>
  );
}
